// <auto-generated />
using System;
using Fro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Fro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fro.Domain.Entities.ConfigurationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnName("name");

                    b.Property<string>("RegeneratorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnName("regenerator_type");

                    b.HasKey("Id");

                    b.ToTable("configuration_templates", (string)null);
                });

            modelBuilder.Entity("Fro.Domain.Entities.OptimizationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<double?>("BestObjectiveValue")
                        .HasColumnName("BestObjectiveValue");

                    b.Property<string>("BestSolution")
                        .HasColumnType("JSON")
                        .HasColumnName("best_solution");

                    b.Property<string>("CeleryTaskId")
                        .HasMaxLength(255)
                        .HasColumnName("celery_task_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentIteration")
                        .HasColumnName("current_iteration");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(255);

                    b.Property<double>("Progress")
                        .HasColumnName("progress");

                    b.Property<string>("Results")
                        .HasColumnType("JSON")
                        .HasColumnName("results");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("optimization_jobs", (string)null);
                });

            modelBuilder.Entity("Fro.Domain.Entities.OptimizationScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnName("algorithm");

                    b.Property<Guid>("BaseConfigurationId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("base_configuration_id");

                    b.Property<string>("BoundsConfig")
                        .HasColumnType("JSON");

                    b.Property<string>("ConstraintsConfig")
                        .HasColumnType("JSON");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignVariables")
                        .IsRequired()
                        .HasColumnType("JSON")
                        .HasColumnName("design_variables");

                    b.Property<int?>("MaxFunctionEvaluations");

                    b.Property<int>("MaxIterations")
                        .HasColumnName("max_iterations");

                    b.Property<int?>("MaxRuntimeMinutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .HasMaxLength(100);

                    b.Property<string>("ObjectiveWeights")
                        .HasColumnType("JSON");

                    b.Property<string>("OptimizationConfig")
                        .IsRequired()
                        .HasColumnType("JSON")
                        .HasColumnName("optimization_config");

                    b.Property<string>("ScenarioType")
                        .HasMaxLength(50);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<double>("Tolerance")
                        .HasColumnName("tolerance");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BaseConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("optimization_scenarios", (string)null);
                });

            modelBuilder.Entity("Fro.Domain.Entities.RegeneratorConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid?>("BasedOnTemplateId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("based_on_template_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedSteps")
                        .HasColumnType("JSON")
                        .HasColumnName("completed_steps");

                    b.Property<string>("ConfigurationVersion")
                        .HasMaxLength(20)
                        .HasColumnName("configuration_version");

                    b.Property<string>("ConstraintsConfig")
                        .HasColumnType("JSON")
                        .HasColumnName("constraints_config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStep")
                        .HasColumnName("current_step");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FlowConfig")
                        .HasColumnType("JSON")
                        .HasColumnName("flow_config");

                    b.Property<string>("GeometryConfig")
                        .HasColumnType("JSON")
                        .HasColumnName("geometry_config");

                    b.Property<bool>("IsTemplate")
                        .HasColumnName("is_template");

                    b.Property<bool>("IsValidated")
                        .HasColumnName("is_validated");

                    b.Property<string>("MaterialsConfig")
                        .HasColumnType("JSON")
                        .HasColumnName("materials_config");

                    b.Property<string>("ModelGeometry")
                        .HasColumnType("JSON")
                        .HasColumnName("model_geometry");

                    b.Property<string>("ModelMaterials")
                        .HasColumnType("JSON")
                        .HasColumnName("model_materials");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnName("name");

                    b.Property<string>("RegeneratorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnName("regenerator_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnName("status");

                    b.Property<string>("ThermalConfig")
                        .HasColumnType("JSON")
                        .HasColumnName("thermal_config");

                    b.Property<int>("TotalSteps")
                        .HasColumnName("total_steps");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("JSON")
                        .HasColumnName("validation_errors");

                    b.Property<double?>("ValidationScore")
                        .HasColumnName("validation_score");

                    b.Property<string>("ValidationWarnings")
                        .HasColumnType("JSON")
                        .HasColumnName("validation_warnings");

                    b.Property<string>("VisualizationConfig")
                        .HasColumnType("JSON")
                        .HasColumnName("visualization_config");

                    b.HasKey("Id");

                    b.HasIndex("BasedOnTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("regenerator_configurations", (string)null);
                });

            modelBuilder.Entity("Fro.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("DATETIME")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("DATETIME")
                        .HasColumnName("reset_token_expires");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Fro.Domain.Entities.OptimizationJob", b =>
                {
                    b.HasOne("Fro.Domain.Entities.OptimizationScenario", "Scenario")
                        .WithMany("OptimizationJobs")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Fro.Domain.Entities.OptimizationScenario", b =>
                {
                    b.HasOne("Fro.Domain.Entities.RegeneratorConfiguration", "BaseConfiguration")
                        .WithMany("OptimizationScenarios")
                        .HasForeignKey("BaseConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fro.Domain.Entities.User", "User")
                        .WithMany("OptimizationScenarios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseConfiguration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fro.Domain.Entities.RegeneratorConfiguration", b =>
                {
                    b.HasOne("Fro.Domain.Entities.ConfigurationTemplate", "Template")
                        .WithMany("Configurations")
                        .HasForeignKey("BasedOnTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fro.Domain.Entities.User", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fro.Domain.Entities.ConfigurationTemplate", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Fro.Domain.Entities.OptimizationScenario", b =>
                {
                    b.Navigation("OptimizationJobs");
                });

            modelBuilder.Entity("Fro.Domain.Entities.RegeneratorConfiguration", b =>
                {
                    b.Navigation("OptimizationScenarios");
                });

            modelBuilder.Entity("Fro.Domain.Entities.User", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("OptimizationScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
