"""fix_optimization_scenario_status_field

Revision ID: 003_fix_opt_status
Revises: 002_add_default_users
Create Date: 2025-10-01 12:38:43.783400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '003_fix_opt_status'
down_revision: Union[str, None] = '002_add_default_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # Fix optimization_scenarios.status field to use 'active' instead of scenario_type values
    # Update existing records that might have scenario_type values in status field
    op.execute("""
        UPDATE optimization_scenarios
        SET status = 'active'
        WHERE status IN ('baseline', 'geometry_optimization', 'material_optimization',
                        'operating_conditions', 'comprehensive')
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)

    # ### end Alembic commands ###